services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    command: mongod --bind_ip_all
    volumes:
      - mongodb_data:/data/db
    networks:
      - ms-network

  ms-student:
    build: .
    container_name: ms-student
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB=${MONGO_DB}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - mongodb
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge

volumes:
  mongodb_data: